title: DjangoCon US
url: "https://2017.djangocon.us"
author : DjangoCon US

include:
  - _pages
  - .surgeignore

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .editorconfig
  - .gitignore
  - bower.json
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - README.md
