title: DjangoCon US
url: "https://2017.djangocon.us"
author : DjangoCon US

include:
  - _pages
  - .surgeignore

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - octopress-autoprefixer

exclude:
  - .editorconfig
  - .gitignore
  - bower.json
  - bower_components
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - README.md

sass:
    style: compressed
