title: DjangoCon US
url: "https://2017.djangocon.us"
include:
  - _pages

# Build settings
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

sass:
    style: compressed
